In [1]:
from numpy import random, zeros

In [19]:
def queue(l,u,N,c):
    
    ### from github code, doesnt make costumers wait
    
    inter_arrival_times= random.exponential(scale=1/l, size=N)
    service_times= random.exponential(scale=1/u, size= N)
    
    arrival_times=zeros(N)
    arrival_times[0]=inter_arrival_times[0]
    
    departure_times=zeros(N)
    departure_times[0]=arrival_times[0]+service_times[0]
    
    for i in range(1,N):
        arrival_times[i]=arrival_times[i-1]+ inter_arrival_times[i]
        departure_times[i]=arrival_times[i]+service_times[i]
        
    total_times=departure_times-arrival_times
    waiting_times=total_times-service_times

    return inter_arrival_times, service_times, arrival_times, departure_times, total_times, waiting_times

In [20]:
queue(1,2,10,1)

(array([0.69566097, 2.52957016, 6.1006207 , 1.81087423, 0.11737018,
        0.55408165, 0.95605533, 0.56576782, 0.65314805, 1.50813935]),
 array([1.19071586, 0.98256119, 1.00011645, 0.53554553, 1.93044743,
        0.02138211, 0.05960712, 0.30238962, 0.25286218, 2.34747144]),
 array([ 0.69566097,  3.22523113,  9.32585183, 11.13672606, 11.25409624,
        11.80817789, 12.76423322, 13.33000104, 13.98314909, 15.49128845]),
 array([ 1.88637683,  4.20779232, 10.32596828, 11.67227159, 13.18454367,
        11.82956   , 12.82384034, 13.63239066, 14.23601127, 17.83875989]),
 array([1.19071586, 0.98256119, 1.00011645, 0.53554553, 1.93044743,
        0.02138211, 0.05960712, 0.30238962, 0.25286218, 2.34747144]),
 array([ 0.00000000e+00, -2.22044605e-16, -2.22044605e-16,  4.44089210e-16,
         0.00000000e+00, -6.07153217e-16,  2.35922393e-16,  8.32667268e-16,
         3.88578059e-16, -4.44089210e-16]))

In [17]:
    ####### from Ross book

def queue2(l,u,N,T):
    t=0
    
    N_A, N_D= 0, 0
    t_A=random.exponential(1/l)
    A=zeros(N)
    D=zeros(N)

    while min(t_A, t_D)<T:
        if t_A<=t_D & t_A<=T:
            t=t_A
            N_A+=1
            n+=1
            A[N_A]=t
            t_A=t+random.exponential(1/l)
            if n==1:
                t_D=t+random.exponential(1/u)

        elif t_D<t_A & t_D<T:
            t=t_D
            n-=1
            N_D+=1
            if n==0:
                t_D=10**5
            else:
                t_D=t+random.exponential(1/u)   

    if n=0: 
        T_p=max(t-T,0)
    else:
        t=t_D
        n-=1
        N_D+=1
        D[N_D]=t
        

    return A,D,T_p

IndentationError: expected an indented block after function definition on line 3 (2051256071.py, line 4)

In [6]:
queue

NameError: name 'queue2' is not defined